### DISCUSSION TITLE
[Help Needed] Cookies not being set

### DISCUSSION THREAD

**Discussion by Kubura33** [manchenkoff/nuxt-auth-sanctum#372] [Q&A] [answered]
Hey, I am having the similar issue that is presented here : https://github.com/manchenkoff/nuxt-auth-sanctum/discussions/353
This is my configuration: 
I am using an image from serversideup
I have set my /etc/hosts to be 127.0.0.1 api.onlyme.local 
This is my docker compose for Laravel API : 

```
version: '3.8'

services:
    api.onlyme.local:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:8080"
        networks:
            - nuxt-laravel
        depends_on:
            - mysql
        environment:
            APP_ENV: local
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: MathLab
            DB_USERNAME: MathLab
            DB_PASSWORD:

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: MathLab
            MYSQL_USER: MathLab
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - nuxt-laravel


networks:
    nuxt-laravel:
        external: true
        driver: bridge
volumes:
    mysql_data:
```
   

And this is from Nuxt: 
    version: "3.9"

```services:
 nuxt:
    build:
      context: .
      target: dev
    container_name: onlyme.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - nuxt-laravel
networks:
  nuxt-laravel:
    driver: bridge
    external: true
```

I have set SESSION_DOMAIN to ".onlyme.local" in my .env. I keep getting : nuxt-auth-sanctum:csr:warn CSRF token mismatch, check your API configuration

My nuxt config

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  debug: true,
  ssr: true,
  modules: [
    '@nuxt/eslint',
    '@nuxtjs/tailwindcss',
    'nuxt-auth-sanctum'
  ],
  sanctum:{
    baseUrl: 'http://api.onlyme.local:8080',
    headers:{
      'Content-Type': "application/json",
      "Accept": "application/json"
    }
    },
  tailwindcss: {
    exposeConfig: true,
    viewer: true
  }
})
```
I access my front end via localhost:3000, the cookies arent being set, I have followed the stuff from the discussion I sent above but no use... I am using Breeze's starter kit for the API. These are 2 seperate containers join to the same network...
