### ISSUE TITLE
[Help needed] After login, user does not persist. What I'm doing wrong?

### ISSUE THREAD

**Issue by rafailml** [manchenkoff/nuxt-auth-sanctum#122]
I'm using "nuxt-auth-sanctum": "^0.4.2", with Laravel 11.08 and Sanctum 4.02. I have two docker containers, one for Nuxt 8.3.1 and one for Laravel.

I'm able to log in user with:
```
await login(credentials)
```
Then I'm redirected to index page which is behind auth middleware:
```
middleware: ['sanctum:auth']
```
I'm able to see logged in user in index page:
```
const { user } = useSanctumAuth<User>()
console.log(user)
```
Also I can see matching requests in Laravel Telescope. I can see authenticated user in Laravel.
But, after I hit refresh, when I'm on my index page, I'm redirected back to login page. Which means that user is not authenticated. 
Reading src/runtime/middleware/sanctum.auth.ts there are: 
```
if (isAuthenticated.value === true) {
        return;
}
```
So, somehow user is not authenticated ?!?!?

Returning back to index page, I'm redirected to login. In Docker logs I see: 
```
[nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "http://localhost:8004/api/user": <no response> fetch failed
```

Digging deeper, I found that this comes from src/runtime/plugin.ts: 
```
try {
            logger.debug('Fetching user identity on plugin initialization');
            user.value = await client(options.endpoints.user);
        } catch (error) {
            handleIdentityLoadError(error as Error, logger);
        }
```
But there is nothing in Teleport. So it seams that this does not hit Laravel at all.
I found similar problem here: #57 but It does not help. But when I turn SSR off it works.

What I'm doing wrong?

My nuxt.config.ts:
```
const sanctumConfig = {
  baseUrl: 'http://localhost:8004', 
  origin: 'http://localhost:3004', 
  mode: 'cookie',
  endpoints: {
    login: '/api/login',
    logout: '/api/logout',
    user: '/api/user',
  },
  redirect: {
    onAuthOnly: '/auth/login',
    onGuestOnly: '/',
    onLogout: '/auth/login',
    onLogin: '/',
    keepRequestedRoute: true,
  },
  logLevel: 5,
}

export default defineNuxtConfig({
  // ssr: false,
  devtools: { enabled: true },
  modules: [
    '@nuxt/test-utils/module',
    'nuxt-auth-sanctum',
  ],
  sanctum: sanctumConfig,
}
```

**Comment by manchenkoff** [comment]
Hey @rafailml, I assume you have SSR mode enabled according to what you posted in the description. So, once you hit refresh, Nuxt tries to send a request to your Laravel application, which is not available from the Docker container at `localhost:3004`, but it is available under the container name (usually `laravel.test` when you use Sail).

In your case, you should use actual domain instead of localhost referring, I also posted more details about [here](https://github.com/manchenkoff/nuxt-auth-sanctum/issues/115#issuecomment-2190177530)

**Comment by rafailml** [comment]
Ok, here is my docker-compose.yaml for Laravel side:
```
name: site_api

services:
    site_app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: dev
        entrypoint: php artisan octane:frankenphp --max-requests=1 --port=8000
        ports:
            - 8004:8000
        volumes:
            - .:/app
        networks:
            - dockernet
networks:
    dockernet:
```

Here is my Nuxt docker-compose.yaml:
```
name: site_front

services:
  site_node:
    container_name: site_front
    ports:
      - '3004:3000'
    build:
      context: .
      target: dev
      dockerfile: docker/Dockerfile
    environment:
      HOST: 0.0.0.0
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - dockernet
volumes:
  node_modules:
networks:
  dockernet:
```

Now my nuxt.config.ts looks like:
```
const sanctumConfig = {
  baseUrl: 'http://site_app', // Laravel base URL
  origin: 'http://localhost:3004', // Nuxt base URL
  mode: 'cookie',
  endpoints: {
    login: '/api/login',
    logout: '/api/logout',
    user: '/api/user',
  },
  redirect: {
    onAuthOnly: '/auth/login',
    onGuestOnly: '/',
    onLogout: '/auth/login',
    onLogin: '/',
    keepRequestedRoute: true,
  },
  logLevel: 5,
}
```   

In my /etc/hosts file I have:
```
127.0.0.1       site_api-site_app
::1             site_api-site_app
127.0.0.1       site_app
::1             site_app
```

but I'm getting same result:
```
[nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "http://site_app/api/user": <no response> fetch failed
```

setting 
```
baseUrl: 'http://site_app:8004',
```
gives the same result. Also:
```
baseUrl: 'http://site_api-site_app',
or
baseUrl: 'http://site_api-site_app:8004',
```
