### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by nizukameha** [manchenkoff/nuxt-auth-sanctum#283]
**Describe the bug**

I can't figure out why I keep getting this cors error :
![{4046DC8B-81AC-4407-A54F-A952EACA4BB3}](https://github.com/user-attachments/assets/946e5d8d-0a84-4390-8cc1-4a8a820cfb4a)

**To Reproduce**

Try to login to your Laravel backend.

**Expected behavior**

I expect to login.

**Actual behavior**

I keep getting cors errors.

**Module information**

-   Version: `0.5.4`
-   Content of your `nuxt.config.ts`:

```typescript
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  modules: ['@nuxt/ui', '@pinia/nuxt', 'nuxt-auth-sanctum'],
  ui: {
    primary: 'violet',
    gray: 'cool'
  },
  sanctum: {
    baseUrl: 'http://api.messagerie-ws.local',
    mode: 'cookie',
    logLevel: 5
  },
})
```

**Nuxt environment:**

-   Version: `3.15.1`
-   SSR Enabled: **yes**
-   Environment: **local**

**Laravel environment:**

-   Version: `11.31`
-   Sanctum installed via Breeze: **no**
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: **yes**
-   What is your session domain in `config/session.php`: `.messagerie-ws.local`
-   What is your stateful domains in `config/sanctum.php`: `messagerie-ws.local`
-   Content of `config/cors.php`:

```php
<?php
return [
    'paths' => ['api/*', 'sanctum/csrf-cookie'],
    'allowed_methods' => ['*'],
    'allowed_origins' => [env('SANCTUM_STATEFUL_DOMAINS')],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,
];
```

**Logs**
```log
nuxt-auth-sanctum:csr:debug [request] added default headers ['Accept']0: "Accept"length: 1[[Prototype]]: Array(0)
browser.mjs?v=3ea7b938:48 nuxt-auth-sanctum:csr:debug [request] added csrf token header ['X-XSRF-TOKEN']0: "X-XSRF-TOKEN"length: 1[[Prototype]]: Array(0)
browser.mjs?v=3ea7b938:48 nuxt-auth-sanctum:csr:trace Request headers for "/login" {accept: 'application/json', x-xsrf-token: 'eyJpdiI6IjFEUHRmSDRJV1hWY0E4YU1GODZCZ1E9PSIsInZhbH…0YWZjZjQ5NDBkYzgwMTNmNGJhZWE0N2Q5IiwidGFnIjoiIn0='}
```

**Additional context**

I also can provide my docker-compose file in order to have more context.
```yml
services:
  laravel:
    container_name: messagerie-ws-api
    build:
      context: '../messagerie-ws-api/vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-router.rule=Host(`api.messagerie-ws.local`)"
      - "traefik.http.routers.api-router.entrypoints=web"
      - "traefik.http.services.laravel-backend.loadbalancer.server.port=80"
      - "traefik.http.services.laravel-backend.loadbalancer.passHostHeader=true"
      - "traefik.docker.network=traefik"
    env_file:
      - ../messagerie-ws-api/.env
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '../messagerie-ws-api:/var/www/html'
    networks:
      - traefik
    depends_on:
      - mysql
      - redis

  nuxt:
    container_name: messagerie-ws-front
    build:
      context: ../messagerie-ws-front
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-router.rule=Host(`messagerie-ws.local`)"
      - "traefik.http.routers.front-router.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    volumes:
      - '../messagerie-ws-front:/app'
    networks:
      - traefik

  # Service MySQL
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    env_file:
      - ../messagerie-ws-api/.env
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - traefik

  traefik:
    image: 'traefik:v2.5'
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--providers.docker.defaultRule="
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard Traefik
      - "8081:8081" # Websocket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  traefik:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
```
