### ISSUE TITLE
Docker containerization

### ISSUE THREAD

**Issue by Jonston** [manchenkoff/nuxt-auth-sanctum#352]
Good afternoon! What if laravel api and nuxt application are in different containers, but I want to use cookie-based authorization? Setting `baseUrl=http://laravel:8000` results in crossdomain requests and cookie issues. Thank you!

**Comment by manchenkoff** [comment]
Hey @Jonston! This can be solved by naming you Laravel app the same way as domain would be. For example, Laravel container name - `api.myapp.test`.

Then you can setup an entry in your `/etc/hosts` (depends on your OS), to make `api.myapp.test` accessible from the web browser.

In this case, CSR requests will go to `api.myapp.test` -> resolved to docker -> passed into Laravel container
For SSR, requests will go directly to the container named `api.myapp.test` (they should be in the same network)

You can check more details in the following discussions:
- #58 
- #115 
- #57 
- #13

**Comment by Jonston** [comment]
I'm having difficulty setting up nginx. The server and client seem to be configured normally, but communication between the Nuxt -> Laravel container is problematic. Could you help me?
backand docker-compose.yml
```yml
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api.events.local
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network
            - shared-network
        depends_on:
            - mysql
        env_file:
            - .env

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network
        ports:
            - "3306:3306"

networks:
    laravel-network:
        driver: bridge
    shared-network:
        external: true

volumes:
    mysql-data:
        driver: local
```
Frontend docker-compose.yml
```yml
services:
    nuxt:
        build: .
        container_name: events
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
        networks:
            - nuxt-network
            - shared-network

networks:
    nuxt-network:
        driver: bridge
    shared-network:
        external: true
```
nginx default.conf
```conf
upstream backend {
    server api.events.local:9000;
}

upstream nuxt {
    server nuxt:3000;
}

server {
    listen 80;
    server_name api.events.local;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

server {
    listen 80;
    server_name events.local; # Или как ты хочешь обращаться

    location / {
        proxy_pass http://nuxt;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```
Буду очень признателен за помощь
